メモアプリを作成しました。
3maigenkou/memo_practice pull request #1
Opened 2021-11-25 00:55 UTC by 3maigenkou

ご確認よろしくお願いいたします。

2021-11-30 02:05 UTC, u1tnk requested changes
構成とうは概ね良いのですが変数名やviewへの渡し方を改善した方が良いので対応お願いします。

2021-11-30 02:05 UTC, u1tnk commented on app.rb
> +  json = {id: "#{id}", title: "#{title}", comment: "#{comment}" }
字下げがおかしいですね。 rubocop通ってますか？

2021-11-30 02:05 UTC, u1tnk commented on app.rb
> +  @load_files = sort_files.map do |file|
viewに渡す変数名としては load_filesはおかしいですね。 変数名は中身のデータに即した名前にしましょう。

2021-11-30 02:05 UTC, u1tnk commented on app.rb
> +  @id = memo['id']
小さい規模なので問題無いのですが、属性が増えると大変なのでmemoを `@memo`としてviewに渡した方が良いと思います。

2021-12-03 02:29 UTC, sanmaigenkou commented on app.rb
> +  json = {id: "#{id}", title: "#{title}", comment: "#{comment}" }
申し訳ないです、最終的にrubocop通すのを失念していました💦改善いたしました。

2021-12-03 02:29 UTC, 3maigenkou commented on app.rb
> +  @load_files = sort_files.map do |file|
変数名を'memo_contents'に変更しました。

2021-12-03 02:33 UTC, 3maigenkou commented on app.rb
> +  @id = memo['id']
`@memo`としてviewに渡しました。

2021-12-04 03:48 UTC, u1tnk approved these changes

2021-12-14 23:18 UTC, merged